services:
  qwen3_tts:
    image: jimlee2048/qwen3-tts:latest
    container_name: qwen3-tts
    ports:
      - "7860:7860"
    environment:
      ATTN_IMPLEMENTATION: kernels-community/flash-attn
      # Hugging Face cache root inside the container
      HF_HOME: /root/.cache/huggingface
      # For Chinese Mainland users, you may need to use a mirror HuggingFace endpoint
      # HF_ENDPOINT: https://hf-mirror.com
    # To persist model cache on the host, bind mount the HF_HOME:
    # volumes:
    #   - /path/to/huggingface:/root/.cache/huggingface
    gpus: all
    restart: unless-stopped
